trigger:
  tags:
    include:
      - v*
  branches:
    include:
      - "*"

stages:
  - stage: "Test"
    jobs:
      - job: windows64
        pool: { vmImage: "vs2017-win2016" }
        steps:
          - task: UsePythonVersion@0
          - script: |
              choco install --yes --limit-output --pre tesseract
              choco install --yes --limit-output python3
              choco install --yes --limit-output ghostscript
              choco install --yes --limit-output qpdf
              choco install --yes --limit-output pngquant
          - script: |
              pip install --upgrade pip wheel
              pip install -r requirements/main.txt -r requirements/test.txt .
              tesseract --version
              qpdf --version
          - powershell: |
              $env:path = "C:\Program Files\Tesseract"
              pytest -n auto
